CREATE TABLE IF NOT EXISTS ca_user_task_profiles (
  discord_user_id VARCHAR(32) NOT NULL PRIMARY KEY,
  rerolls_available INT NOT NULL DEFAULT 3,
  completion_reward_batches INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
