CREATE TABLE IF NOT EXISTS ca_rsn_tier_rewards (
  rsn VARCHAR(32) NOT NULL PRIMARY KEY,
  highest_rewarded_tier_rank INT NOT NULL DEFAULT 0,
  highest_rewarded_tier_label VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
